// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVFOsUCz4Hik8kie6O1w99sD3_9sZl07g',
    appId: '1:290299167511:web:051dac1d06c7de4efeed52',
    messagingSenderId: '290299167511',
    projectId: 'avisa-mais-15b07',
    authDomain: 'avisa-mais-15b07.firebaseapp.com',
    storageBucket: 'avisa-mais-15b07.appspot.com',
    measurementId: 'G-382ZZS8K40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlKgsQmK6SHEaFMnZrdydVmfZXLknmTto',
    appId: '1:290299167511:android:8825427bd2013792feed52',
    messagingSenderId: '290299167511',
    projectId: 'avisa-mais-15b07',
    storageBucket: 'avisa-mais-15b07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR0WB1J8JC4kp4bT3swl_-erCjVk0FVNc',
    appId: '1:290299167511:ios:96913b964d7f31c3feed52',
    messagingSenderId: '290299167511',
    projectId: 'avisa-mais-15b07',
    storageBucket: 'avisa-mais-15b07.appspot.com',
    iosBundleId: 'com.example.avisaMais',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR0WB1J8JC4kp4bT3swl_-erCjVk0FVNc',
    appId: '1:290299167511:ios:96913b964d7f31c3feed52',
    messagingSenderId: '290299167511',
    projectId: 'avisa-mais-15b07',
    storageBucket: 'avisa-mais-15b07.appspot.com',
    iosBundleId: 'com.example.avisaMais',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVFOsUCz4Hik8kie6O1w99sD3_9sZl07g',
    appId: '1:290299167511:web:90d68c5cb16b4d6cfeed52',
    messagingSenderId: '290299167511',
    projectId: 'avisa-mais-15b07',
    authDomain: 'avisa-mais-15b07.firebaseapp.com',
    storageBucket: 'avisa-mais-15b07.appspot.com',
    measurementId: 'G-V9Y0NVHV0C',
  );

}